name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  generate-exe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: pattern_gen
          path: src/dist/windows

  release:
    runs-on: ubuntu-latest
    needs: [generate-exe]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}

      - name: Upload Artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: src/dist/windows/pattern_gen.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: find-latest-tag
      # - uses: oprypin/find-latest-tag@v1
      #   with:
      #     repository: bradday4/SIM_GENERATOR # The repository to scan.
      #     releases-only: true # We know that all relevant tags have a GitHub release for them.
      #   id: SIM_GENERATOR # The step ID to refer to later.
      # - run: echo "SIM_GENERATOR is at version ${{ steps.SIM_GENERATOR.outputs.tag }}"
