name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}

  generate-exe:
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: pattern_gen
          path: src/dist/windows

  upload-exe-to-releases:
    needs: [release, generate-exe]
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - src/dist/windows/pattern_gen.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
